### ISSUE TITLE
Best way to handle Configuration Errors in React

### ISSUE THREAD

**Issue by yevhen-logosha** [recurly/react-recurly#64] opened 2020-05-05 10:39 UTC
Guys, whats your idea behind catching Configuration errors eg `invalid-public-key` in React.
At the moment, I get uncaught error upon submitting form with intentionally passed invalid public key. Since its coming from your `iframe` it is not clear how to handle it. 
please advise. many thanks!
<img width="602" alt="Screenshot 2020-05-05 at 17 52 54" src="https://user-images.githubusercontent.com/25623699/81080351-50186b80-8ef9-11ea-956b-7d82daefc2b3.png">

**Comment by chrissrogers** [comment] 2020-05-05 19:53
For configuration errors, `react-recurly` follows https://github.com/recurly/recurly-js conventions. When an error is caused by configuration, it's severe enough to warrant an uncatchable error like the one in your screenshot -- it's expected that the implementation should be fixed (using the correct public key) without providing a way to handle it at runtime. Basically, any error that an end-user could never fix.

For user land errors like those that occur during tokenization (empty name, invalid cc number, etc), the respective callback provides error handling.

**Closed by chrissrogers** 2020-05-05 19:53 UTC
Labels: question
